version: "2"

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - goconst
    - mnd
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - whitespace
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      enable-all: true
    nolintlint:
      require-explanation: true
      require-specific: true
    wsl:
      allow-assign-and-anything: true
      allow-cuddle-declarations: true
      allow-assign-and-call: true
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - "github.com/uber/h3-go/v4"
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - dupl
          - gosec
          - govet

formatters:
  enable:
    - gofmt
    - goimports

run:
  issues-exit-code: 1
