/*
 * Copyright 2026 Uber Technologies, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package h3go

import (
	"errors"
)

// Vertex is an H3 index that identifies a single topological vertex, shared by
// three cells. One of the three neighboring cells is chosen as the vertex owner
// (the cell with the lowest numerical index), which fixes the vertex's canonical
// index and geographic coordinates.
type Vertex int64

// directionIndexOffset is subtracted from a direction digit to index the
// per-pentagon face table, whose entries start at the J axis.
const directionIndexOffset = 2

var (
	// pentagonDirectionFaces maps each pentagon base cell to the icosahedron faces
	// found in each axial direction, in order starting at the J axis. Generated by
	// the upstream generatePentagonDirectionFaces script.
	pentagonDirectionFaces = [NumPentagons]struct {
		baseCell int
		faces    [numPentVerts]int
	}{
		{4, [numPentVerts]int{4, 0, 2, 1, 3}},
		{14, [numPentVerts]int{6, 11, 2, 7, 1}},
		{24, [numPentVerts]int{5, 10, 1, 6, 0}},
		{38, [numPentVerts]int{7, 12, 3, 8, 2}},
		{49, [numPentVerts]int{9, 14, 0, 5, 4}},
		{58, [numPentVerts]int{8, 13, 4, 9, 3}},
		{63, [numPentVerts]int{11, 6, 15, 10, 16}},
		{72, [numPentVerts]int{12, 7, 16, 11, 17}},
		{83, [numPentVerts]int{10, 5, 19, 14, 15}},
		{97, [numPentVerts]int{13, 8, 17, 12, 18}},
		{107, [numPentVerts]int{14, 9, 18, 13, 19}},
		{117, [numPentVerts]int{15, 19, 17, 18, 16}},
	}

	// directionToVertexNumHex maps a hexagon direction digit to its first vertex
	// number (same face). Direction 0 (center) is unused.
	directionToVertexNumHex = [numDigits]int{invalidDigit, 3, 1, 2, 5, 4, 0}

	// directionToVertexNumPent maps a pentagon direction digit to its first vertex
	// number (same face). Directions 0 (center) and 1 (deleted K axis) are unused.
	directionToVertexNumPent = [numDigits]int{invalidDigit, invalidDigit, 1, 2, 4, 3, 0}

	// vertexNumToDirectionHex maps a hexagon vertex number to its direction digit.
	vertexNumToDirectionHex = [numHexVerts]int{
		ijAxesDigit, jAxesDigit, jkAxesDigit, kAxesDigit, ikAxesDigit, iAxesDigit,
	}

	// vertexNumToDirectionPent maps a pentagon vertex number to its direction digit.
	vertexNumToDirectionPent = [numPentVerts]int{
		ijAxesDigit, jAxesDigit, jkAxesDigit, ikAxesDigit, iAxesDigit,
	}

	// revNeighborDirectionsHex maps a direction digit to the reverse direction from
	// the neighbor in that direction, given as an index into directions to allow
	// rotation. Direction 0 (center) is unused.
	revNeighborDirectionsHex = [numDigits]int{invalidDigit, 5, 3, 4, 1, 0, 2}
)

// vertexRotations returns the number of counterclockwise 60° rotations of the
// cell's vertex numbers relative to the directional layout of its neighbors.
func (c Cell) vertexRotations() (int, error) {
	fijk, err := c.toFaceIjk()
	if err != nil {
		return 0, err
	}

	baseCell := c.BaseCellNumber()
	cellLeadingDigit := c.leadingNonZeroDigit()
	baseFijk := baseCellHomeFijk[baseCell]
	ccwRot60 := baseCellToCCWrot60(baseCell, fijk.face)

	if !isBaseCellPentagon[baseCell] {
		return ccwRot60, nil
	}

	// Find the direction-to-face mapping for this pentagon base cell. A pentagon
	// base cell always appears in the table, so the lookup always succeeds.
	var dirFaces [numPentVerts]int

	for i := range pentagonDirectionFaces {
		if pentagonDirectionFaces[i].baseCell == baseCell {
			dirFaces = pentagonDirectionFaces[i].faces
			break
		}
	}

	// Additional CCW rotation for polar neighbors or IK neighbors.
	if fijk.face != baseFijk.face &&
		(isBaseCellPolarPentagon(baseCell) ||
			fijk.face == dirFaces[ikAxesDigit-directionIndexOffset]) {
		ccwRot60 = (ccwRot60 + 1) % 6
	}

	// Adjust when the cell crosses a deleted pentagon subsequence.
	switch {
	case cellLeadingDigit == jkAxesDigit && fijk.face == dirFaces[ikAxesDigit-directionIndexOffset]:
		// Crosses from JK to IK: rotate CW.
		ccwRot60 = (ccwRot60 + 5) % 6
	case cellLeadingDigit == ikAxesDigit && fijk.face == dirFaces[jkAxesDigit-directionIndexOffset]:
		// Crosses from IK to JK: rotate CCW.
		ccwRot60 = (ccwRot60 + 1) % 6
	}

	return ccwRot60, nil
}

// vertexNumForDirection returns the first vertex number for the given direction;
// the neighbor in that direction lies between this vertex number and the next in
// sequence. It returns invalidVertexNum if the direction is not valid.
func (c Cell) vertexNumForDirection(direction int) int {
	isPent := c.IsPentagon()
	if direction == centerDigit || direction >= invalidDigit || (isPent && direction == kAxesDigit) {
		return invalidVertexNum
	}

	rotations, err := c.vertexRotations()
	if err != nil {
		return invalidVertexNum
	}

	if isPent {
		return (directionToVertexNumPent[direction] + numPentVerts - rotations) % numPentVerts
	}

	return (directionToVertexNumHex[direction] + numHexVerts - rotations) % numHexVerts
}

// directionForVertexNum returns the direction for the neighbor between the given
// vertex number and the next in sequence, or invalidDigit if the vertex number
// is not valid for the cell.
func (c Cell) directionForVertexNum(vertexNum int) int {
	isPent := c.IsPentagon()
	maxVerts := numHexVerts

	if isPent {
		maxVerts = numPentVerts
	}

	if vertexNum < 0 || vertexNum > maxVerts-1 {
		return invalidDigit
	}

	rotations, err := c.vertexRotations()
	if err != nil {
		return invalidDigit
	}

	if isPent {
		return vertexNumToDirectionPent[(vertexNum+rotations)%numPentVerts]
	}

	return vertexNumToDirectionHex[(vertexNum+rotations)%numHexVerts]
}

// Vertex returns the topological vertex of the cell with the given vertex
// number. Hexagons have six vertexes (0–5) and pentagons five (0–4).
func (c Cell) Vertex(vertexNum int) (Vertex, error) {
	cellNumVerts := numHexVerts
	if c.IsPentagon() {
		cellNumVerts = numPentVerts
	}

	res := c.Resolution()

	if vertexNum < 0 || vertexNum > cellNumVerts-1 {
		return 0, ErrDomain
	}

	// By convention the owner is the neighboring cell with the lowest index;
	// default to the cell itself and lower it as neighbors are examined.
	owner := c
	ownerVertexNum := vertexNum

	// The center child always has the lowest index among its neighbors, so the
	// owner search can be skipped for it.
	if res == 0 || indexDigit(c, res) != centerDigit {
		var err error

		owner, ownerVertexNum, err = c.vertexOwner(vertexNum, cellNumVerts, res)
		if err != nil {
			return 0, err
		}
	}

	vertex := owner.setMode(vertexMode).setReservedBits(ownerVertexNum)

	return Vertex(vertex), nil
}

// vertexOwner determines the owning cell and its vertex number for a vertex of c
// shared with two neighbors. The owner is the cell with the lowest index among
// the three; its vertex number is translated into the owner's own numbering.
func (c Cell) vertexOwner(vertexNum, cellNumVerts, res int) (Cell, int, error) {
	owner := c
	ownerVertexNum := vertexNum

	// Left neighbor of the vertex, with its rotations.
	left := c.directionForVertexNum(vertexNum)
	if left == invalidDigit {
		return 0, 0, ErrFailed
	}

	leftNeighbor, lRotations, err := c.neighborRotations(left, 0)
	if err != nil {
		return 0, 0, err
	}

	if leftNeighbor < owner {
		owner = leftNeighbor
	}

	// Skip the right neighbor if the left is already known to be lowest.
	if res == 0 || indexDigit(leftNeighbor, res) != centerDigit {
		// Vertex numbers are counterclockwise, so vertex-1 is the right side.
		right := c.directionForVertexNum((vertexNum - 1 + cellNumVerts) % cellNumVerts)

		rightNeighbor, rRotations, rightErr := c.neighborRotations(right, 0)
		if rightErr != nil {
			return 0, 0, rightErr
		}

		if rightNeighbor < owner {
			owner = rightNeighbor
			dir := owner.vertexDirectionToCell(c, right, rRotations)
			ownerVertexNum = owner.vertexNumForDirection(dir)
		}
	}

	if owner == leftNeighbor {
		ownerIsPentagon := owner.IsPentagon()
		dir := owner.vertexDirectionToCell(c, left, lRotations)

		// The left neighbor uses the second vertex of the shared edge, which may
		// wrap around the vertex numbering.
		ownerVertexNum = owner.vertexNumForDirection(dir) + 1
		if ownerVertexNum == numHexVerts || (ownerIsPentagon && ownerVertexNum == numPentVerts) {
			ownerVertexNum = 0
		}
	}

	return owner, ownerVertexNum, nil
}

// vertexDirectionToCell returns the direction from the owner cell back to cell.
// A pentagon owner is resolved directly; otherwise the reverse of the stepping
// direction is rotated into the owner's coordinate space.
func (c Cell) vertexDirectionToCell(cell Cell, direction, rotations int) int {
	if c.IsPentagon() {
		return c.directionForNeighbor(cell)
	}

	return directions[(revNeighborDirectionsHex[direction]+rotations)%numHexVerts]
}

// CellToVertex returns the topological vertex of the cell with the given vertex
// number.
func CellToVertex(c Cell, vertexNum int) (Vertex, error) {
	return c.Vertex(vertexNum)
}

// Vertexes returns all topological vertexes of the cell: six for a hexagon, or
// five for a pentagon (the sixth slot is omitted).
func (c Cell) Vertexes() ([]Vertex, error) {
	isPent := c.IsPentagon()
	out := make([]Vertex, 0, numHexVerts)

	for i := range numHexVerts {
		if i == numPentVerts && isPent {
			continue
		}

		vertex, err := c.Vertex(i)
		if err != nil {
			return nil, err
		}

		out = append(out, vertex)
	}

	return out, nil
}

// CellToVertexes returns all topological vertexes of the cell.
func CellToVertexes(c Cell) ([]Vertex, error) {
	return c.Vertexes()
}

// LatLng returns the geographic coordinates of the vertex in degrees.
func (v Vertex) LatLng() (LatLng, error) {
	vertexNum := reservedBits(v)
	owner := ownerCell(v)

	fijk, err := owner.toFaceIjk()
	if err != nil {
		return LatLng{}, err
	}

	res := owner.Resolution()

	var boundary CellBoundary
	if owner.IsPentagon() {
		boundary = fijk.pentToCellBoundary(res, vertexNum, 1)
	} else {
		boundary = fijk.toCellBoundary(res, vertexNum, 1)
	}

	return boundary[0], nil
}

// VertexToLatLng returns the geographic coordinates of the vertex in degrees.
func VertexToLatLng(vertex Vertex) (LatLng, error) {
	return vertex.LatLng()
}

// IsValid reports whether the index is a valid, canonical H3 vertex.
func (v Vertex) IsValid() bool {
	if modeOf(v) != vertexMode {
		return false
	}

	vertexNum := reservedBits(v)
	owner := ownerCell(v)

	if !owner.IsValid() {
		return false
	}

	// Reconstructing the vertex from its owner is the simplest way to confirm the
	// vertex number is in range and the index is canonical.
	canonical, err := owner.Vertex(vertexNum)
	if err != nil {
		return false
	}

	return v == canonical
}

// IsValidVertex reports whether the index is a valid H3 vertex.
func IsValidVertex(v Vertex) bool {
	return v.IsValid()
}

// Resolution returns the resolution of the vertex.
func (v Vertex) Resolution() int {
	return resolution(v)
}

// IndexDigit returns the indexing digit of the vertex at res, for res in
// [1, MaxResolution].
func (v Vertex) IndexDigit(res int) (int, error) {
	return indexDigitChecked(v, res)
}

// VertexFromString returns a Vertex parsed from its hexadecimal string
// representation. Callers should validate it with Vertex.IsValid before use.
func VertexFromString(s string) Vertex {
	//nolint:gosec // an H3 index is a 64-bit value; uint64->int64 is a lossless reinterpretation.
	return Vertex(IndexFromString(s))
}

// String returns the hexadecimal string representation of the vertex.
func (v Vertex) String() string {
	//nolint:gosec // an H3 index is a 64-bit value; int64->uint64 is a lossless reinterpretation.
	return IndexToString(uint64(v))
}

// MarshalText implements the encoding.TextMarshaler interface.
func (v Vertex) MarshalText() ([]byte, error) {
	return []byte(v.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (v *Vertex) UnmarshalText(text []byte) error {
	*v = VertexFromString(string(text))
	if !v.IsValid() {
		return errors.New("invalid vertex index")
	}

	return nil
}
